### ISSUE TITLE
Add tag if not present

### ISSUE THREAD

**Issue by skynet-05** [Consuma/release-management#1]
## Input Tag ["First time only"]
https://github.com/Consuma/release-management/blob/0ae9678179e64b2da60b42888aaed5e2ac250564/action.yml#L50
After the above line we can add an input
```
firstRelease:
    description: 'Insert Tag (**Only if no Tags present before) [default: 1.0.0]'
    required: false
    default: false
    type: boolean
```

## Conditions to Insert First Tag
https://github.com/Consuma/release-management/blob/0ae9678179e64b2da60b42888aaed5e2ac250564/entrypoint.sh#L15
Edit the above line
```
if ( '$firstRelease' = true) 
then
    git tag -a v1.0.0 -m "First Tag" 
    git push origin v1.0.0
    LATEST_VERSION=$(git describe --abbrev=0 --tags)
else
    LATEST_VERSION=$(git describe --abbrev=0 --tags)
fi
```
